### ISSUE TITLE
【質問】最新版ソースの取込

### ISSUE THREAD

**Issue by TatsunoriH** [kuturogi99with99jazz/java-leaning-project#24]
課題実行手順-課題の実施 (2)の「5.作成した開発ブランチに対して本家リポジトリから最新版を取り込みます。」についてハードコピーで張ってある内容にならず、課題内容が取り込めずにいます。
Remoteに本家リポジトリを選択とありますが、https://github.com/kuturogi99with99jazz/java-leaning-project.gitが選択されている状態でいいのでしょうか？ただ選択するとBranches to merge で origin/masterが表示されません。同期ボタンを押下してもでてきませんでした。
もしわかりましたらご教示お願いいたします。

**Comment by kuturogi99with99jazz** [comment]
アカウントが１つしかないので先生は100%生徒の状態で実施できないのがつらいところですが、origin/master以外になにか表示されますでしょうか？とりあえずスクショをとってくれると助かります。画面コピー→Slackメッセージでctrl+vで可能です。

**Comment by kuturogi99with99jazz** [comment]
> jinoue先生の確認が済んでマージした後にやったほうが良いかもしれません。
マージしました。

**Comment by jinoue666** [comment]
![image](https://user-images.githubusercontent.com/49367815/56289811-c61a2b00-615c-11e9-8cac-e050c1bd4266.png)
Remote定義の追加

**Comment by TatsunoriH** [comment]
上記手順で取り込むことができました。
ありがとうございました。

**Comment by kuturogi99with99jazz** [comment]
解決したのでクローズ
